USE [dbTeste]
GO

/****** Object:  Table [dbo].[CAD_AUTOR]    Script Date: 01/15/2013 13:58:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CAD_AUTOR](
	[ID_AUTOR] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TXT_NOME] [varchar](50) NOT NULL,
	[DAT_NASCIMENTO] [date] NOT NULL,
	[DAT_FALECIMENTO] [date] NULL,
	[TXT_COMENTARIO] [varchar](500) NULL,
	[TXT_EMAIL] [varchar](50) NULL,
	[NUM_TELEFONE] [numeric](14, 0) NULL,
	[NUM_COD_TELEFONE] [numeric](3, 0) NULL,
 CONSTRAINT [PK_CAD_AUTOR] PRIMARY KEY CLUSTERED 
(
	[ID_AUTOR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

